export const names = {
    // @keep-sorted
    ...{
        base: "__VLS_base",
        componentsOption: "__VLS_componentsOption",
        ctx: "__VLS_ctx",
        defaultModels: "__VLS_defaultModels",
        defaults: "__VLS_defaults",
        directives: "__VLS_directives",
        directivesOption: "__VLS_directivesOption",
        dollars: "__VLS_dollars",
        emit: "__VLS_emit",
        export: "__VLS_export",
        exposed: "__VLS_exposed",
        intrinsics: "__VLS_intrinsics",
        modelEmit: "__VLS_modelEmit",
        props: "__VLS_props",
        propsOption: "__VLS_propsOption",
        self: "__VLS_self",
        setup: "__VLS_setup",
        slots: "__VLS_slots",
    },
    // @keep-sorted
    ...{
        Emit: "__VLS_Emit",
        EmitProps: "__VLS_EmitProps",
        GlobalComponents: "__VLS_GlobalComponents",
        InheritedAttrs: "__VLS_InheritedAttrs",
        LocalComponents: "__VLS_LocalComponents",
        LocalDirectives: "__VLS_LocalDirectives",
        ModelEmit: "__VLS_ModelEmit",
        ModelProps: "__VLS_ModelProps",
        Props: "__VLS_Props",
        PublicProps: "__VLS_PublicProps",
        RootEl: "__VLS_RootEl",
        SetupExposed: "__VLS_SetupExposed",
        Slots: "__VLS_Slots",
        StyleModules: "__VLS_StyleModules",
        TemplateRefs: "__VLS_TemplateRefs",
    },
};
