shamefullyHoist: true

packages:
  - playground

catalog:
  "@types/node": ^25.0.7
  "@types/picomatch": ^4.0.2
  "@typescript/native-preview": 7.0.0-dev.20260114.1
  "@vue/compiler-dom": ^3.5.26
  "@vue/language-core": ^3.2.2
  "@vue/shared": ^3.5.26
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.3.2
  clerc: ^1.2.1
  empathic: ^2.0.0
  eslint: ^9.39.2
  mlly: ^1.8.0
  muggle-string: ^0.4.1
  oxc-parser: ^0.108.0
  oxc-resolver: ^11.16.2
  oxc-walker: ^0.6.0
  pathe: ^2.0.3
  picomatch: ^4.0.3
  pkg-types: ^2.3.0
  tinyglobby: ^0.2.15
  tsconfck: ^3.1.6
  tsdown: ^0.19.0
  vitest: ^4.0.17
  vue: ^3.5.26
  zx: ^8.8.5
