shamefullyHoist: true

packages:
  - playground

catalog:
  "@types/node": ^25.0.10
  "@types/picomatch": ^4.0.2
  "@typescript/native-preview": 7.0.0-dev.20260114.1
  "@vue/compiler-dom": ^3.5.27
  "@vue/language-core": ^3.2.3
  "@vue/shared": ^3.5.27
  "@zinkawaii/eslint-config": ^0.4.1
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.4.0
  clerc: 1.3.0-beta.1
  empathic: ^2.0.0
  eslint: ^9.39.2
  mlly: ^1.8.0
  muggle-string: ^0.4.1
  oxc-parser: ^0.110.0
  oxc-resolver: ^11.16.4
  oxc-walker: ^0.7.0
  pathe: ^2.0.3
  picomatch: ^4.0.3
  pkg-types: ^2.3.0
  tinyexec: ^1.0.2
  tinyglobby: ^0.2.15
  tsconfck: ^3.1.6
  tsdown: ^0.20.1
  vitest: ^4.0.18
  vue: ^3.5.27
