shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*
  - playground

overrides:
  rolldown: 1.0.0-rc.5
  vite: 8.0.0-beta.15

catalog:
  "@types/node": ^25.3.0
  "@types/picomatch": ^4.0.2
  "@typescript/native-preview": 7.0.0-dev.20260224.1
  "@vue/compiler-dom": ^3.5.29
  "@vue/language-core": ^3.2.5
  "@vue/shared": ^3.5.29
  "@zinkawaii/eslint-config": ^0.4.2
  "@zinkawaii/scripts": ^0.0.3
  "@zinkawaii/tsconfig": ^0.0.2
  bumpp: ^10.4.1
  clerc: ^1.3.1
  empathic: ^2.0.0
  eslint: ^10.0.2
  mlly: ^1.8.0
  muggle-string: ^0.4.1
  oxc-parser: ^0.115.0
  oxc-resolver: ^11.18.0
  oxc-walker: ^0.7.0
  pathe: ^2.0.3
  picomatch: ^4.0.3
  pkg-types: ^2.3.0
  tinyexec: ^1.0.2
  tinyglobby: ^0.2.15
  tsconfck: ^3.1.6
  tsdown: ^0.20.3
  unrun: ^0.2.27
  vitest: ^4.0.18
  vscode-jsonrpc: 9.0.0-next.11
  vscode-languageserver-protocol: 3.17.6-next.16
  vue: ^3.5.29
